language: python
python:
  - 3.7

# Install
install:
  - sudo apt-get -q update
  - sudo apt-get -q install gfortran libblas-dev libatlas-dev liblapack-dev
  - pip3 install python-coveralls
  - pip3 install coverage
  - python3 setup.py -q install

# Test
script: 
  - nosetests --with-coverage

# Coveralls
after_success:
  - coveralls